"""add best move feature

Revision ID: 9ba6fa261a9e
Revises: 2e4e3b8b3ba6
Create Date: 2026-03-27 12:51:03.061380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba6fa261a9e'
down_revision: Union[str, None] = '2e4e3b8b3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_move_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('guessed_seat_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'guessed_seat_number', name='uq_game_guess')
    )
    op.add_column('games', sa.Column('killed_first_night_seat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'killed_first_night_seat')
    op.drop_table('best_move_guesses')
    # ### end Alembic commands ###
